language: python
python:
  - "3.5"
  - "3.6"

dist: trusty

addons:
  sonarcloud:
    organization: "jhawk1196"
    token: ${SONAR}

before_install:
  - pip install coverage

script:
  - coverage run --source=./ -m unittest
  - coverage report
  - sonar-scanner
  - sonar.python.coverage.reportPaths

after_success:
  - coveralls